/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface GenericProxyFactoryInterface extends ethers.utils.Interface {
  functions: {
    "create(address,bytes)": FunctionFragment;
    "create2(address,bytes32,bytes)": FunctionFragment;
    "predictDeterministicAddress(address,bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "create",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "create2",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "predictDeterministicAddress",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "create2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictDeterministicAddress",
    data: BytesLike
  ): Result;

  events: {
    "ProxyCreated(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProxyCreated"): EventFragment;
}

export class GenericProxyFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: GenericProxyFactoryInterface;

  functions: {
    create(
      _instance: string,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "create(address,bytes)"(
      _instance: string,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    create2(
      _instance: string,
      _salt: BytesLike,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "create2(address,bytes32,bytes)"(
      _instance: string,
      _salt: BytesLike,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    predictDeterministicAddress(
      _master: string,
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "predictDeterministicAddress(address,bytes32)"(
      _master: string,
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  create(
    _instance: string,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "create(address,bytes)"(
    _instance: string,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  create2(
    _instance: string,
    _salt: BytesLike,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "create2(address,bytes32,bytes)"(
    _instance: string,
    _salt: BytesLike,
    _data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  predictDeterministicAddress(
    _master: string,
    _salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "predictDeterministicAddress(address,bytes32)"(
    _master: string,
    _salt: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    create(
      _instance: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, string] & { instanceCreated: string; result: string }>;

    "create(address,bytes)"(
      _instance: string,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, string] & { instanceCreated: string; result: string }>;

    create2(
      _instance: string,
      _salt: BytesLike,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, string] & { instanceCreated: string; result: string }>;

    "create2(address,bytes32,bytes)"(
      _instance: string,
      _salt: BytesLike,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, string] & { instanceCreated: string; result: string }>;

    predictDeterministicAddress(
      _master: string,
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "predictDeterministicAddress(address,bytes32)"(
      _master: string,
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    ProxyCreated(
      created: string | null,
      implementation: string | null
    ): TypedEventFilter<
      [string, string],
      { created: string; implementation: string }
    >;
  };

  estimateGas: {
    create(
      _instance: string,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "create(address,bytes)"(
      _instance: string,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    create2(
      _instance: string,
      _salt: BytesLike,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "create2(address,bytes32,bytes)"(
      _instance: string,
      _salt: BytesLike,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    predictDeterministicAddress(
      _master: string,
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "predictDeterministicAddress(address,bytes32)"(
      _master: string,
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    create(
      _instance: string,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "create(address,bytes)"(
      _instance: string,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    create2(
      _instance: string,
      _salt: BytesLike,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "create2(address,bytes32,bytes)"(
      _instance: string,
      _salt: BytesLike,
      _data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    predictDeterministicAddress(
      _master: string,
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "predictDeterministicAddress(address,bytes32)"(
      _master: string,
      _salt: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
