/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IdleYieldSourceProxyFactoryInterface extends ethers.utils.Interface {
  functions: {
    "createNewProxy()": FunctionFragment;
    "iGenericProxyFactory()": FunctionFragment;
    "instance()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createNewProxy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "iGenericProxyFactory",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "instance", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "createNewProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "iGenericProxyFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "instance", data: BytesLike): Result;

  events: {};
}

export class IdleYieldSourceProxyFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IdleYieldSourceProxyFactoryInterface;

  functions: {
    createNewProxy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "createNewProxy()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    iGenericProxyFactory(overrides?: CallOverrides): Promise<[string]>;

    "iGenericProxyFactory()"(overrides?: CallOverrides): Promise<[string]>;

    instance(overrides?: CallOverrides): Promise<[string]>;

    "instance()"(overrides?: CallOverrides): Promise<[string]>;
  };

  createNewProxy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "createNewProxy()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  iGenericProxyFactory(overrides?: CallOverrides): Promise<string>;

  "iGenericProxyFactory()"(overrides?: CallOverrides): Promise<string>;

  instance(overrides?: CallOverrides): Promise<string>;

  "instance()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    createNewProxy(
      overrides?: CallOverrides
    ): Promise<[string, string] & { instanceCreated: string; result: string }>;

    "createNewProxy()"(
      overrides?: CallOverrides
    ): Promise<[string, string] & { instanceCreated: string; result: string }>;

    iGenericProxyFactory(overrides?: CallOverrides): Promise<string>;

    "iGenericProxyFactory()"(overrides?: CallOverrides): Promise<string>;

    instance(overrides?: CallOverrides): Promise<string>;

    "instance()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createNewProxy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "createNewProxy()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    iGenericProxyFactory(overrides?: CallOverrides): Promise<BigNumber>;

    "iGenericProxyFactory()"(overrides?: CallOverrides): Promise<BigNumber>;

    instance(overrides?: CallOverrides): Promise<BigNumber>;

    "instance()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createNewProxy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "createNewProxy()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    iGenericProxyFactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "iGenericProxyFactory()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    instance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "instance()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
