/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IIdleTokenHelperInterface extends ethers.utils.Interface {
  functions: {
    "getMintingPrice(address)": FunctionFragment;
    "getRedeemPrice(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getMintingPrice",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRedeemPrice",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getMintingPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRedeemPrice",
    data: BytesLike
  ): Result;

  events: {};
}

export class IIdleTokenHelper extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IIdleTokenHelperInterface;

  functions: {
    getMintingPrice(
      idleYieldToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getMintingPrice(address)"(
      idleYieldToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getRedeemPrice(address,address)"(
      idleYieldToken: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getRedeemPrice(address)"(
      idleYieldToken: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  getMintingPrice(
    idleYieldToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getMintingPrice(address)"(
    idleYieldToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getRedeemPrice(address,address)"(
    idleYieldToken: string,
    user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getRedeemPrice(address)"(
    idleYieldToken: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getMintingPrice(
      idleYieldToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getMintingPrice(address)"(
      idleYieldToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRedeemPrice(address,address)"(
      idleYieldToken: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRedeemPrice(address)"(
      idleYieldToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getMintingPrice(
      idleYieldToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getMintingPrice(address)"(
      idleYieldToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRedeemPrice(address,address)"(
      idleYieldToken: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRedeemPrice(address)"(
      idleYieldToken: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getMintingPrice(
      idleYieldToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getMintingPrice(address)"(
      idleYieldToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRedeemPrice(address,address)"(
      idleYieldToken: string,
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRedeemPrice(address)"(
      idleYieldToken: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
