/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IGenericProxyFactory } from "../IGenericProxyFactory";

export class IGenericProxyFactory__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGenericProxyFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IGenericProxyFactory;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_instance",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "create",
    outputs: [
      {
        internalType: "address",
        name: "instanceCreated",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "result",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
