/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IIdleTokenHelper } from "../IIdleTokenHelper";

export class IIdleTokenHelper__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IIdleTokenHelper {
    return new Contract(address, _abi, signerOrProvider) as IIdleTokenHelper;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "idleYieldToken",
        type: "address",
      },
    ],
    name: "getMintingPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "idleYieldToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getRedeemPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "idleYieldToken",
        type: "address",
      },
    ],
    name: "getRedeemPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
